#! /usr/bin/env node
// -*- js -*-

var JSHINT = require('./lib/jshint').JSHINT,
    print = require('sys').print,
    src = require('fs').readFileSync(__dirname + '/../../build/dist/fea.js', 'utf8')
    config = require('fs').readFileSync(__dirname + '/config.json');

JSHINT(src, eval(config));

var ok = {
	"Expected an identifier and instead saw 'undefined' (a reserved word).": true,
	"Use '===' to compare with 'null'.": true,
	"Use '!==' to compare with 'null'.": true,
	"Expected an assignment or function call and instead saw an expression.": true,
	"Expected a 'break' statement before 'case'.": true,
	"'e' is already defined.": true
};

var e = JSHINT.errors, found = 0, w;

for ( var i = 0; i < e.length; i++ ) {
	w = e[i];

	if ( !ok[ w.reason ] ) {
		found++;
		print( "\n" + w.evidence + "\n" );
		print( "    Problem at line " + w.line + " character " + w.character + ": " + w.reason );
	}
}

if ( found > 0 ) {
	print( "\n" + found + " Error(s) found.\n" );

} else {
	print( "JHLint check passed.\n" );
}
